name: Build Desktop Apps

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Make Gradle executable
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Build package
        run: ./gradlew packageDistributionForCurrentOS
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: desktop-${{ runner.os }}
          path: build/compose/binaries/**